### ISSUE TITLE
Incomplete annotation

### ISSUE THREAD

**Issue by IlkayW** [JustMeZXX/Intelligent-Night-Time-Traffic-Surveillance#1]
I was looking at the head and tail light annotations and found out that there are missing annotations when I was visualizing them.

For example in the first frame of dense_dark_low there is a car bottom left without annotated tail lights.

![dense_dark_rear_00000000](https://user-images.githubusercontent.com/5719971/183028592-61ab2ae9-80d5-475f-982c-5678abc23ac7.png)
(Annotations = blue boxes)

In the second frame the tail lights of this car are annotated

![dense_dark_rear_00000001](https://user-images.githubusercontent.com/5719971/183029080-28467a86-5a46-42c0-8838-23cba0b947b5.png)

The cars in the far back are not annotated as well.

Is this a parsing mistake by me or are the annotations just incomplete?

Greetings,
IlkayW

**Comment by JustMeZXX** [comment]
Hi IlkayW,

Actually, those imcomplete annotations are not a parsing mistake. Because we fused both front and rear view in this work, we have to manually identify their overalpping region, see ROI.mat in dataset. That means we only label the headlights or taillights that are within the pre-defined ROI. If I recall, I use center of bounding box to determine whether I need to retain the annotations. 

I hope this helps.

Thanks
Xinxiang Zhang
