### ISSUE TITLE
Do you have the paired headlights labels available?

### ISSUE THREAD

**Issue by NERVYRZ** [JustMeZXX/Intelligent-Night-Time-Traffic-Surveillance#2]
Hello the authors of this project,

I am also trying to do some research on the topic of nighttime vehicle detection using headlight features. After going through your public dataset, I noticed that you didn't provide the paired ground truth of the vehicles' headlights. Is it possible to provide them so that we can verify the accuracy of paired results?

Thank you so much!

**Comment by JustMeZXX** [comment]
Thanks for you pointing this out.

I do wish that I have the paired ground truth of the vehicles' headlights to share with you, but I do not have it because my research is not related to pairing the headlights. I would suggest you to label the headlight pair by yourself, which I do not think will take too long.
